/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#131313",
        "surface-variant": "#353534",
        "error-container": "#93000a",
        "outline": "#8a9485",
        "on-secondary-fixed-variant": "#343d96",
        "primary-fixed-dim": "#88d982",
        "secondary-container": "#343d96",
        "on-secondary-container": "#a8afff",
        "surface": "#131313",
        "secondary": "#bdc2ff",
        "surface-container-high": "#2a2a2a",
        "inverse-surface": "#e5e2e1",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed": "#000767",
        "tertiary-container": "#b14b6f",
        "outline-variant": "#40493d",
        "surface-container": "#201f1f",
        "surface-dim": "#131313",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#610931",
        "on-secondary": "#1b247f",
        "inverse-on-surface": "#313030",
        "on-background": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "primary-fixed": "#a3f69c",
        "tertiary-fixed-dim": "#ffb1c7",
        "secondary-fixed-dim": "#bdc2ff",
        "on-primary-fixed": "#002204",
        "tertiary": "#ffb1c7",
        "primary": "#88d982",
        "on-tertiary-container": "#ffedf0",
        "on-surface-variant": "#bfcaba",
        "on-surface": "#e5e2e1",
        "on-primary-fixed-variant": "#005312",
        "on-primary": "#003909",
        "inverse-primary": "#1b6d24",
        "surface-tint": "#88d982",
        "tertiary-fixed": "#ffd9e2",
        "on-tertiary-fixed": "#3f001c",
        "error": "#ffb4ab",
        "secondary-fixed": "#e0e0ff",
        "primary-container": "#2e7d32",
        "on-primary-container": "#cbffc2",
        "on-tertiary-fixed-variant": "#7f2448",
        "surface-bright": "#393939",
        "on-error": "#690005"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
    },
  },
  plugins: [],
}
